
```{r, echo=FALSE, fig.pos="H", message=FALSE, warning=FALSE}

# Get Month for each session
session_month <- all_sessions %>% 
  dplyr::select(ID, EndDate) %>% 
  # convert date to first of the month
  mutate(Month = as.Date(paste0(format(EndDate, "%Y-%m"), "-01")))

# Add Month to embeddings
sp_greens_environmental_bills_distance_ft_embeddings <- sp_greens_environmental_bills_distance_ft_embeddings %>% 
  left_join(dplyr::select(session_month, ID, Month), by = c("SubmissionSession" = "ID"))

# Join Embedding Distances with Google Trends
gt_embeddings <- gt_climate_change_2004_2024_cor_plot %>% 
  dplyr::select(Month, climate_change_new) %>% 
  left_join(sp_greens_environmental_bills_distance_ft_embeddings, by = "Month") %>% 
  dplyr::select(-SubmissionSession) %>% 
  drop_na()

# Calculate differences between rows
gt_embeddings$climate_change_new_diff <- c(NA, diff(gt_embeddings$climate_change_new))
gt_embeddings$distance_diff <- c(NA, diff(gt_embeddings$distance))

# hist(gt_embeddings$climate_change_new_diff)
# hist(gt_embeddings$distance_diff)

# Add lag
gt_embeddings <- gt_embeddings %>% mutate(distance_diff_lagged = dplyr::lag(distance_diff, n = 1, default = NA))
  
# Clean up dataframe
gt_embeddings <- gt_embeddings %>% drop_na()

```


```{r cor-plot, echo=FALSE, fig.pos="H", fig.height = 2.5, fig.width = 6, message=FALSE, warning=FALSE, fig.cap = "Correlation Plots"}

plot1 <- ggplot(gt_embeddings, aes(x = climate_change_new_diff, y = distance_diff)) +
  geom_point(size = 1) +
  geom_smooth(method = "lm", se = TRUE, size = 0.5) +  # Thinner geom_smooth() line
  labs(title = NULL,
       x = expression(Delta ~ "Search Term Popularity"),  # Correctly render Δ
       y = expression(Delta ~ "Euclidean Distance")) +
  theme_minimal() +
  theme(axis.title = element_text(size = 10))  # Smaller label font size

plot2 <- ggplot(gt_embeddings, aes(x = climate_change_new_diff, y = distance_diff_lagged)) +
  geom_point(size = 1) +
  geom_smooth(method = "lm", se = TRUE, size = 0.5) +  # Thinner geom_smooth() line
  labs(title = NULL,
       x = expression(Delta ~ "Search Term Popularity")) +
  scale_y_continuous(name = NULL, sec.axis = dup_axis(name = expression(Delta ~ "Lagged Euclidean Distance"))) +  # Add secondary y-axis on the right
  theme_minimal() +
  theme(axis.title = element_text(size = 10),  # Smaller label font size
        axis.title.y.right = element_text(hjust = 0.5),  # Center y-axis label on the right
        axis.title.y.left = element_blank(),  # Remove left y-axis title
        axis.text.y.left = element_blank())  # Remove left y-axis labels

grid.arrange(plot1, plot2, ncol = 2)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
rm(session_month,
   sp_greens_environmental_bills_distance_ft_embeddings,
   gt_embeddings)
```


