## Abstract

Why have parliamentary bills on environmental issues introduced by mainstream left-wing parties and green parties become more similar in content over the past 20 years? Drawing on the literature on political agendas, in particular “party system agendas”, I examine how parties respond to each other's agendas and to issues that are salient to the public. I argue that left-wing parties introduce environmental legislation in order to attract green voters.

Using Switzerland as a case study, I apply a text-as-data approach by measuring the content similarity of parliamentary bills through word embeddings. I find that increased public salience of climate change correlates with a lagged increase in content similarity between environmental bills introduced by the Swiss mainstream left-wing party (SP) and the Swiss Green Party (GPS). This suggests that the SP responds to the GPS agenda with the aim of attracting Green voters, demonstrating how party agendas change in response to electoral pressures.