## Introduction

Parliamentary bills on environmental issues introduced in the Swiss parliament by the Social Democrats (SP) and the Green Party (GPS) have become increasingly similar in content over the past 20 years. This finding results from a text-as-data analysis of these parliamentary bills. By calculating word embeddings for each bill and placing the bills in a high-dimensional semantic space, the change in distance between bills can be measured over time. The bills examined, which were introduced by both parties and dealt with environmental issues, show a decrease in distance in the semantic space, indicating that they have become more semantically similar. Why are these bills becoming more semantically similar?

To answer this question, I use theories of party system agendas to explain why political actors put certain issues on their agendas. Research shows that public salience influences what parties prioritise and that parties respond to each other's agendas, especially when two parties are ideologically close. Following the literature, we can expect that as environmental issues become more salient to the public, mainstream left-wing parties will prioritise these issues by introducing parliamentary bills that are more similar in content to those introduced by green parties. Left-wing parties do this in an attempt to gain an electoral advantage by attracting green voters. I test this hypothesis in Switzerland, focusing specifically on the mainstream left-wing party (SP) and the Green Party (GPS).

To explain the decrease in semantic distance between parliamentary bills, I measure the salience of environmental issues using the popularity of the search term "climate change" in the search engine Google. I model the change in distance with the change in salience using correlations and ordinary least squares linear regression models. I set up two models, one of which uses a lagged outcome, i.e. modelling a time lag between the salience of environmental issues and the similarity of parliamentary bills. The results show that an increase in search term popularity is associated with a lagged increase in content similarity between environmental bills introduced by the SP and the GPS.

The structure of the paper begins with a literature review that examines existing research on how party agendas are influenced and shaped. This is followed by a theory and hypothesis section in which I outline the theoretical framework and present the hypothesis to be tested. Next, I explain why Switzerland is an appropriate case for this study. In the following section, I describe the data used and the natural language processing methods applied to analyse the content of the parliamentary bills. I then describe how the relationship between the dependent and independent variables was measured. Finally, I present the findings of the research, discuss their implications and suggest directions for future research.