## Literature Review and Theory

### Party Agenda Setting

Agendas are considered to be a hierarchy of issues [@green-pedersenWhoSetsAgenda2010 260]. Relevant actors, e.g., political parties, can influence but must also pay attention to these issues. These actors place topics on their agenda that are salient amongst the public [@sidesOriginsCampaignAgendas2006 407]. They do this because setting an agenda, and thus determining what politics is about, is a form of wielding political power [@schattschneiderSemisovereignPeopleRealist1975 68; @edwardsWhoInfluencesWhom1999 327].

One way of placing topics on the agenda is by touching upon these topics in parliamentary bills. These bills are put forward by a variety of actors, one of them being political parties that aim at influencing the “party system agenda”. This is a model that describes how political parties set the agenda in the context of issue competition [@green-pedersenWhoSetsAgenda2010 257]. In this model, the “party system agenda” is influenced by permanent debate among political parties [@green-pedersenWhoSetsAgenda2010 260]. This debate takes on many forms, one of which is the proposal of new bills [@green-pedersenWhoSetsAgenda2010 266].

Parties react to each other’s agendas within the context of this “party system agenda” [@spoonGoingGreenExplaining2014 374]. On the one hand, parties underline issues that provide an advantage to them. However, parties also have to react to all salient issues in the “party system agenda” at any time [@green-pedersenWhoSetsAgenda2010 261], even if they are potentially harmful.

Parties with similar ideology tend to react more responsively to each other than parties with less similar ideology. This phenomena, coined the “party bloc effect” [@green-pedersenAvoidanceEngagementIssue2015 760; @adamsPolicyAdjustmentParties2009 842], is attributable to the ideological vicinity between parties within the same bloc.

This vicinity allows for parties to win over voters from other, ideologically close parties. An example of this “poaching” is provided by @spoonGoingGreenExplaining2014 [375], who shows that if left-wing parties highlight issues typically dominated by green parties (in short, “green issues”), these left-wing parties can reap potential electoral benefits. In the specific context of Swiss politics, there are two further reasons why left-wing parties would want to highlight “green issues”.

First, “green issues” have become more salient in Switzerland in the past twenty years. @luthElectoralImportanceEvolution2022 [171] show that the electoral importance of energy and environmental issues has increased amongst Swiss voters between 2002 and 2022. This increase in salience is driven by voters [@luthElectoralImportanceEvolution2022 184], thus political parties must react to this development and place “green issues” on their agenda.

Second, I argue that the Swiss Social Democrats (German “Sozialdemokratische Partei der Schweiz”, SP) consider the Swiss Green Party (German “Grüne Schweiz”, GPS) to be an electoral threat. Both parties are ideologically close, i.e., in the same “party bloc” as described above. The GPS has increased their vote share in the Swiss National Council from 7.43% in 2003 to 13.24% in 2019, while the SP has decreased their vote share in the same time span from 23.33% to 16.84%. According to @spoonGoingGreenExplaining2014 [366], a mainstream party such as the SP is more likely to engage with owned issues if niche parties, such as the GPS, is perceived to be an electoral threat. Thus we can expect the SP to counter this threat by addressing green issues with the aim of winning over GPS voters.

Following this argumentation, I posit that parties place topics in the “party system agenda” by putting forward parliamentary bills that, first, touch upon topics that are salient amongst the public and second, are advantageous for the parties themselves.

Following @spoonGoingGreenExplaining2014 [375], left-wing parties put forward bills that touch upon “green topics” in order to gain an electoral benefit. Therefore, in an effort to win over GPS voters, the SP highlights “green issues”. The SP does this by putting forward parliamentary bills that are similar in terms of content to bills put forward by the GPS. This leads to my hypothesis:

**H1**: An increase in the salience of environmental topics among the public leads to an increase in the semantic similarity between SP and Green bills on green topics.

### Calculating Document Similarity with Word Embeddings

In order to test the hypothesis, the semantic similarity between parliamentary bills needs to be measured. This means that the bills’ *content* must be taken into account when performing this comparison. This leads to the realm of natural language processing, short NLP, and text-as-data approaches (2022 Rodriguez). 

- In order to test the hypothesis, the semantic similarity between parliamentary bills has to be measured.
- this means that the *content* of the bills have to be taken into account when comparing parliamentary bills
- this is an issue in the realm of natural language processing, using a text-as-data approach (2022 Rodriguez): how can the semantic similarity between documents, in this case parliamentary bills, be calculated? (2018 Ali, p. 907)

- 2020 wang p. 4: use “word mover’s distance” as a way to measure semantic distance between documents. 
	- this technique uses the concept of text representation in vector space to measure semantic distances between documents.
	- this technique places documents in vector space.
	- “the idea of vector semantics is to represent a word as a point in a multidimensional semantic space” (2024 Jurafsky p. 109)
	- semantically similar documents are closer to each other than disimilar documents. thus the distance between two documents in this vector space allows to make a statement about the similarity of two documents.

- in order to place documents in vector space, a document’s content needs to be converted into word embeddings.
- word embeddings are
	- learned representations of word meanings (2024 Jurafsky, p. 105). in summary, these representations are calculated using the likelihood that a word appears near another word in the same text (2024 Jurafsky, p. 122).
	- these representations take the form of vectors (2024 Jurafsky, p. 109). a vector is simply a list of numbers (2024 Jurafsky, p. 111) that provide a word’s coordinates in vector space.
- word embeddings are good at capturing synonymy, e.g., showing that the words “car” and “automobile” have high semantic similarity (2024 Jurafsky, p. 121). 
- for this reason it is sensible to use word embeddings to measure the semantic distance between documents, in this case parliamentary bills.
- in the realm of political science, word embeddings have also been used to measure candidate positions (2023 Case, p. 11) or party ideology (2019 Rheault, p. 29). they are thus an adequat / tried and tested technique to use to analyse political texts.
- this principle of word embeddings can be translated onto documents, whereby an entire document forms a point in vector space instead of a single word (2014 Le)

- in sum: i place parliamentary bills in vector space in order to measure the similarity between them. the more similar two bills, the smaller the distance between them in vector space.