## Literature Review

Political agendas are a hierarchy of issues [@green-pedersenWhoSetsAgenda2010 260], whereby issues constitute problems that are important to voters (1996 Petrocik, p. 826). Relevant actors, such as political parties, influence this hierarchy of issues. Actors put issues on their agendas that are salient to the public [@sidesOriginsCampaignAgendas2006 407]. Defining and influencing agendas is important because it determines what politics is about and is therefore a way of exercising political power [@schattschneiderSemisovereignPeopleRealist1975 68; @edwardsWhoInfluencesWhom1999 327].

Parties respond to each other’s agendas as part of the “party system agenda” [@spoonGoingGreenExplaining2014 374]. This is a model that describes how political parties set the agenda in the context of issue competition [@green-pedersenWhoSetsAgenda2010 257]. In this model, the ongoing debate between political parties influences the “party system agenda” [@green-pedersenWhoSetsAgenda2010 260], whereby parties emphasise issues that bring an advantage for themselves. However, parties also have to respond to all salient issues in the “party system agenda” at all times [@green-pedersenWhoSetsAgenda2010 261], even if they are potentially damaging.

Parties with similar ideologies tend to be more responsive to each other than parties with less similar ideologies. This phenomenon, called the “party bloc effect” [@green-pedersenAvoidanceEngagementIssue2015 760; @adamsPolicyAdjustmentParties2009 842], is due to the ideological proximity between parties within the same bloc or party family.

What underpins this phenomenon? First, @green-pedersenAvoidanceEngagementIssue2015 [750] show that parties in the same bloc share issue preferences and thus have a common interest in focusing on the same issues. Second, the authors explain that in a multiparty system, parties from the same party bloc are likely to be governmental coalition partners. In order to present themselves as a credible government alternative, parties from the same bloc need to show likeness by focusing on similar issues. Third, @adamsPolicyAdjustmentParties2009 [828] show how an ideological spatial argument supports the “party bloc effect”. The authors explain how parties that are close to each other in an ideological space, shift their policy positions when other parties in close proximity change their policy positions, as both parties, due to their ideological proximity, compete for a very similar set of voters. On the other hand, if a party that is ideologically further away shifts its policy position, the first party has no immediate reason to adjust its own position as a reaction.

When exploring how different parties within left-wing party families respond to each other’s agendas regarding environmental issues, the literature presents varied results. On one hand, @abou-chadiNichePartySuccess2016 [431] indicates that mainstream left-wing parties tend to de-emphasize green issues, recognizing green parties as the successful owners of these environmental topics. On the other hand, @spoonGoingGreenExplaining2014 [375] points out that when left-wing parties do focus on environmental issues, they stand to gain electorally, which enables them to attract voters from green parties. However, for these electoral benefits to materialize, certain conditions must be met: first, the environmental issue in question must be highly salient among the public, enhancing the likelihood of gaining votes through green mobilization. Second, the electoral system needs to be accommodating to smaller parties, and third, the green party must be perceived as a significant electoral threat by left-wing parties [@spoonGoingGreenExplaining2014 372, 375, 366].

In the next section, I develop theoretical expectations based on the framework by @spoonGoingGreenExplaining2014 and apply it to the Swiss case.
