## Data & Methods
`back up statement that embeddings can be used to measure distance between texts and that using this method is legit in the context of comparing parliamentary bills`

### embeddings
`embeddings: how they show the similarity between texts; how they can encompass/convey the meaning of a text as a numerical value `

- there are different ways of measuring different party’s policy positions.
	- one way is to use party manifestos (2014 Green (see p. 752 for description of manual approach); 2022 Lüth p. 177; 2013 Dolezal, p. 63), e.g. using the Comparative Manifesto Project (CMP) (2009 adams p. 829). however, this approach relies on manual labour, which limits the scope of available data.

	- ==[other techniques?]==

	- another way is a text-as-data-approach using natural language processing (NLP) techniques (2022 Rodriguez), whereby the specific NLP technique of “word embeddings” is “well-suited to pick up on important semantic relationships in text related to political phenomenon such as candidate positioning” (2023 Case, p. 11) or party ideology (2019 Rheault, p. 29).

- i use word embeddings to measure semantic distances between different bills: the more similar two bills, the smaller the distance between them


- exploratory data analysis
	- current analysis (number of bills over time etc)
	- show number of bills by party strength; divide number of bills from a party by seats in parliament
- using embeddings, measure difference between texts
	- euclidean distance
	- cosine similarity
	- show difference between grouped by session and grouped by year, as there are outlier session where only few bills are introduced; maybe also filter out “Sondersessionen”, as these are very short and sometimes only cover a certain topic
- measuring distance between SP and greens over time 
	- on all topics: distance is constant
	- on environmental topics: distance decreases
	- differentiate between bills that only have the tag “environment” and bills with the most common co-tag, e.g. “environment” and “finance” 
- does one party move closer to the other party or do both parties move?

### Operationalisation
- Environmental Topic saliency
	- Google Trends?
	- Worry Barometer?
	- selects survey, as done by 2022 Lütch p. 171

### Model
y = distance between sp and greens
x = (lagged?) topic salience