### Data

<!--
Step 1: State what data you use and why. Justify your choice of data. Cite the data and say where it is available
-->

#### Parliamentary Bills
My analysis covers 2841 parliamentary bills^[Parliamentary bills include the following nine types of parliamentary proposals that are possible to introduce in the Swiss parliament (translation provided by the Swiss parliament unless stated otherwise): Parliamentary Initiative (“Parlamentarische Initiative”), Question (“Anfrage”), Urgent Question (own translation: “Dringliche Anfrage”), Interpellation (“Interpellation”), Urgent Interpellation (own translation: “Dringliche Interpellation”), Motions (“Motion”), Postulates (“Postulat”), Question Time – Question (“Fragestunde – Frage”), Petitions (“Petition”)] that include the tag “Environment” (German: “Umwelt”).^[Employees of the Parliamentary Services tag bills with one or several of the following terms that were developed by the Parliamentary Library (Source: Personal email communication with the media spokesperson for the Parliamentary Services): National Policy ("Staatspolitik"), General Law ("Recht Allgemein"), International Politics ("Internationale Politik"), Economy ("Wirtschaft"), Parliament ("Parlament"), Finance ("Finanzwesen"), Social Issues ("Soziale Fragen"), Transportation ("Verkehr"), Environment ("Umwelt"), Urban Planning and Housing ("Raumplanung und Wohnungswesen"), Health ("Gesundheit"), Education ("Bildung"), Media and Communication ("Medien und Kommunikation"), Security Policy ("Sicherheitspolitik"), Agriculture ("Landwirtschaft"), Migration ("Migration"), Science and Research ("Wissenschaft und Forschung"), European Policy ("Europapolitik"), Culture ("Kultur"), Energy ("Energie"), Civil Law ("Zivilrecht"), Employment and Labor ("Beschäftigung und Arbeit"), Human Rights ("Menschenrechte"), Criminal Law ("Strafrecht"), International Law ("Internationales Recht"), Taxation ("Steuer"), Social Protection ("Sozialer Schutz"), Judiciary ("Gerichtswesen”). Own translation from German to English.] These bills were introduced by the SP and GPS party or by their members of parliament in both chambers of the Swiss parliament, namely the National Council (“Nationalrat”) or the Council of States (“Ständerat”). The parliamentary bills are provided by the open data webservices of the Swiss parliament.^[https://www.parlament.ch/de/%C3%BCber-das-parlament/fakten-und-zahlen/open-data-web-services, retrieved 12 May 2024] These webservices are made accessible through the R package “swissparl” [@zumbachSwissparlInterfaceWebservices2021].

Due to Switzerland’s four official languages, parliamentary items of business can be written either in German, French, Italian or Romansh. The Federal Administration (German: “Bundesverwaltung”) translates most items of business in  to German, French and Italian. Some are only translated into German and French.^[https://www.parlament.ch/de/%C3%BCber-das-parlament/parlamentsw%C3%B6rterbuch/parlamentsw%C3%B6rterbuch-detail?WordId=206, retrieved 14 May 2024] In the context of this research, I have chosen to use parliamentary bills in German, as my German is more proficient than my French, simplifying the examination process.

The bills under examination were introduced between March 2004 and December 2023. I choose this time frame because it coincides with the electoral rise of the GPS and also covers a substantial time frame before the increased salience of environmental issues starting in the beginning of the 2010s. This allows for a before-after comparison.

I continue with a brief overview of descriptive statistics of the parliamentary bills. […]

<!--
- EDA
	- number of all/environmental bills over time
	- number of SP/GPS bills over time
	- show number of bills by party strength; divide number of bills from a party by seats in parliament
	- word counts of different groups of bills over time to show that the bills are roughly all the same length
-->

#### Public Salience of Environmental Issues
@luthElectoralImportanceEvolution2022 [171] use the “Swiss Election Study” (Selects)^[https://forscenter.ch/projects/selects/, retrieved 12 May 2024] to measure the salience of environmental issues in the public sphere. In this survey, respondents are asked what their “most important problem” is (Variable “mip1”). I calculate the share of respondents who chose “Environment & Energy” as their most important problem at the time of survey from a list of different issues.^[All issues respondents could pick as their “most important problem”: Agriculture, economics, education and youth & culture, environment & energy, European integration, finances & taxes, gender issues & discrimination, immigration & asylum, international relations&conflicts and foreign policy & army, labour market, law & order, political system and parties & politicians, public health, public service & infrastructure, regions & national cohesion, social security, other problems, no problem, don’t know / no answer / wildcode.] This provides a solid measurement of the public salience of environmental issues. However, the Selects survey is only carried out every four years during Swiss parliamentary elections, thus providing only four data points in my time range of examination (2007, 2011, 2015 and 2019). This stands in contrast to the number of sessions in this time period that I will use to group parliamentary bills by (see further below). I thus need a way of measuring public salience of environmental topics on a more frequent basis.

I turn to Google Trends^[https://trends.google.com, retrieved 12 May 2024] as an alternative way to measure public salience. Google Trends is a tool that enables the evaluation of public interest in specific search terms and topics [@nghiemAnalysisCapacityGoogle2016 10]. Data on Google Trends are available from 2004 onwards. I examine the monthly popularity of the search term “climate change” in Switzerland between January 2004 and May 2024. I pick the search term “climate change” because it is largely congruent with the same issues that the Selects question described above touches upon. It is thus an adequat way of measuring public salience of environemtal topics.

<!--
compare selects with google trends
A brief comparison of both measures show that both Selects and Google Trends generally follow a similar trend line on environmental issues. This underlines the legitimacy of using Google Trends as a way of measuring public salience of environmental topics.
[Add plot from 08_google_trends.R]
-->


### Operationalisation
<!--
Step 2: Measurement – if you create a new measure using the data, explain how you do so. This could include describing coding procedures, the creation of an index, or other forms of measurement.
-->

#### Dependent Variable: Semantic Similarity using Word Embeddings
In order to test the hypothesis, it is necessary to measure the content similarity between parliamentary bills. This leads into the realm of natural language processing, short NLP, and approaches that use text as data [@rodriguezWordEmbeddingsWhat2022]. In NLP terms, how can the semantic similarity between documents, in particular parliamentary bills, be calculated [@aliSemanticSimilarityMeasures2018 907]?

The “Word Mover's Distance” is a method proposed by @wangMeasurementTextSimilarity2020 [4] for measuring the semantic distance between documents. This technique applies the concept of text representation in semantic space as a means of measuring similarity. The underlying principle is to represent a text as a point in a multidimensional semantic space [@jurafskySpeechLanguageProcessing2009 109]. In this space, texts that are semantically similar are positioned closer to each other than texts that are dissimilar. Consequently, the distance between two texts in this space can be used to make a statement about their semantic similarity.

In order to place text in this semantic space, the meaning of a text must be converted into embeddings. These embeddings are learned representations of word meanings [@jurafskySpeechLanguageProcessing2009 97]. In short, these representations are computed using the probability of a word appearing near another word in the same text [@jurafskySpeechLanguageProcessing2009 122]. The representations take the form of vectors [@jurafskySpeechLanguageProcessing2009 109], which are simply a list of numbers [@jurafskySpeechLanguageProcessing2009 111] that represent the location of a text in semantic space.

Embeddings are good at recognising synonyms, e.g., showing that the words “car” and “automobile” have a high semantic similarity [@jurafskySpeechLanguageProcessing2009 121]. This principle of embedding single words can be extended to whole documents, where a document represents a point in the semantic space instead of a single word [@leDistributedRepresentationsSentences2014]. Thus embeddings can be used to measure the similarity between documents, in this case parliamentary bills. In political science, embeddings have also been used to measure the positions of candidates [@caseMeasuringStrategicPositioning2023 11] and party ideology [@rheaultWordEmbeddingsAnalysis2020 29]. They are thus a tried and tested technique for analysing political texts. 

Parties introduce different numbers of bills in each parliamentary session.^[The Swiss parliament meets in four ordinary three-week sessions per year. Additionally, the parliament assembles for further sessions, named “special” or “extraordinary” sessions that deal with issues that were not dealt with in the ordinary sessions (https://www.parlament.ch/en/%C3%BCber-das-parlament/parlamentsw%C3%B6rterbuch/parlamentsw%C3%B6rterbuch-detail?WordId=197, retrieved 10 May 2024).] For this reason, and also because it does not make sense to compare single parliamentary bills with each other, I group all bills put forward by a party in a session and calculate the “middle point” of these bills in the semantic space. This middle point can be found by calculating the average position of all documents in a group.

This centroid represents the overall semantic content of all bills in a group. In other words, the “middle point” reflects the overall semantic content of a party in a session. It effectively summarizes the collective characteristics or the “average” bill within a group, thus identifying the group’s central tendencies and general direction of content. The distance between two groups in semantic space, i.e., two middle points, can be calculated using the Euclidean distance measure. This measure requires the coordinates of two points in order to calculate the distance between these points. The coordinates of the middle points are given, thus calculating the distance can be performed with the function X in the programming language R.

To sum up, in order to measure the semantic similarity between the parliamentary bills introduced by the SP and GPS, I place these bills in semantic space. I then group the bills by party and session and then calculate the middle point of each group. Using the Euclidean distance measure, I calculate the distance between the middle points of groups in semantic space. The more semantically similar two groups of bills are, the smaller the distance between them in semantic space.

I continue with an overview of descriptive statistics of the semantic similarity between bills introduced by the two parties. […]

<!--
- EDA
	- descriptive statistics of distance between the two parties
	- measuring distance between SP and greens over time 
		- on all topics: distance is constant
		- on environmental topics: distance decreases
		- differentiate between bills that only have the tag “environment” and bills with the most common co-tag, e.g. “environment” and “finance” 
	- does one party move closer to the other party or do both parties move?

- nice to have: show difference between grouped by session and grouped by year, as there are outlier session where only few bills are introduced; maybe also filter out “Sondersessionen”, as these are very short and sometimes only cover a certain topic
-->

#### Independent Variable: Salience of Environmental Issues with Google Trends
Google Trends provides a positive integer value to measure the “search interest” of a term within a specific time frame and geographic region.^[https://trends.google.com, retrieved 13 May 2024] These values are scaled between 0 and 100, reflecting a topic's proportion relative to all searches across all topics.^[https://support.google.com/trends/answer/4365533?hl=en&ref_topic=6248052&sjid=14532437735057784414-EU, retrieved 13 May 2024] When examining the search term "climate change" in Switzerland between January 2004 and May 2024, there is an outlier in April 2022. This is likely due to the United Nation’s Intergovernmental Panel on Climate Change (IPCC) report published in April 2022,^[https://www.ipcc.ch/report/sixth-assessment-report-working-group-3/] which was widely discussed in the media.

This outlier, with a value of 100, causes the rest of the data series to display relatively low variation due to the way Google Trends scales values (see line A in Figure X _(add figure)_). This low variation becomes more apparent when comparing the Google Trends data up until March 2022 (see line B in Figure X _(add figure)_). Low variation is problematic for modeling the data later on, as it makes effects less pronounced. To restore the variation lost in the time series that includes April 2022, I recalculated each value by following these steps: First, I calculate the relative change of each value in the shorter series with respect to the first value, obtaining the "multiplier." Second, I align the starting points of both series by adding a value of X to the longer series. Third, I multiply each value in the longer series by the "multiplier" from the first step. This results in a more pronounced variation in the longer series that mirrors the shorter series (see line C in Figure X _(add figure)_).