### Methods

<!--
In this section, you will describe the precise method that you use to test the relationship between your dependent variable and your independent variable.
-->

#### Differencing and Time Lag
Due to the limited scope of this seminar paper, I keep the analysis simple by examining the variable change between observations instead of creating a time series model. To do this, I calculate the change in both the independent and dependent variables from one parliamentary session to the next and use these as my new independent and dependent variables. In the next step, I lag the dependent variable by one unit, i.e., by one session. This approach aims to model the delayed effect of environmental topics in the public sphere on parties and the parliamentary bills they introduce as a reaction. In other words, I assume a delay in parties reacting to an increase in public salience.

### Correlation
In a first step, I calculate the correlation between the dependent and independent variables using the Pearson Correlation. This method is appropriate as an initial, simple examination to see if there is a correlation between the two variables. Since both variables need to be normally distributed for the correlation to hold, I log-transform the dependent variable. 

<!--
- check assumptions: see https://ademos.people.uic.edu/Chapter22.html
- I then compare the unlagged and lagged dependent variables.
-->

### Linear Regression
In a second step, I model the relationship of the differences using linear regression to determine if there is a linear relationship between the two variables. Given the data, this is the best-suited method because it allows me to test the relationship between two continuous variables.

**Model Specifications**

Change in semantic distance between SP and Greens = β + change in Google Trends Topic Salience + error

Lagged change in semantic distance between SP and Greens = β + change in Google Trends Topic Salience + error
