## Conclusion

The aim of this paper is to examine why parliamentary bills on environmental issues introduced by mainstream left-wing parties and green parties have become more similar in content over the past 20 years. To answer this question, I turn to the literature on political agendas, in particular "party system agendas". In this context, parties place issues on their agendas that are salient to the public and respond to each other's agendas. One way of putting issues on the agenda is to introduce parliamentary bills dealing with those issues. 

Research shows that parties that are ideologically close to each other tend to be more responsive to each other's agendas. Specifically, in the context of mainstream left-wing parties and green parties, left-wing parties focus on environmental issues in order to attract green voters. For this to happen, three conditions need to be met: high public salience of environmental issues, an electoral system that favours smaller parties, and the perception of the Green party as a significant electoral threat by left-wing parties. Following the literature, we can assume that when environmental issues become more salient to the public, mainstream left-wing parties will put environmental issues on the "party system agenda" by introducing parliamentary bills that address environmental topics.

In order to test this assumption, I turn to Switzerland. Switzerland is well-suited for this examination because environmental issues have become more salient among the public in the past 20 years. Additionally, Switzerland has an electoral system that is beneficial for small parties, and the Social Democrats (SP), the mainstream left-wing party, perceive the Green Party (GPS) as an electoral threat due to the GPS’s electoral success and ideological proximity.

I apply a text-as-data approach and measure the content similarity of parliamentary bills introduced by the SP and GPS on environmental topics using word embeddings. These bills are placed in semantic space and grouped by party and parliamentary session. I then calculate the centre of each group and measure the Euclidean distance between the SP and GPS centres over time. To explain the change in distance between groups of parliamentary bills, I measure the salience of environmental issues amongst the public by using the popularity of the search term “climate change” provided by Google Trends. The results indicate that an increase in search term popularity is associated with a lagged increase in content similarity between parliamentary bills introduced by the SP and the GPS. This suggests that the SP is reacting to the GPS agenda, perceiving it as an electoral threat and aiming to win over green voters.

Future research should apply more time-series specific analyses, as the present study does not take this into account. In addition to the Euclidean distance used to measure semantic similarity between parliamentary bills, other similarity measures should be considered, such as the Word Mover's Distance [@kusnerWordEmbeddingsDocument2015] or more advanced geometric approaches, such as the method proposed by @heidarianHybridGeometricApproach2016. When exploring pre-trained word embedding alternatives, future research could benefit from an approach where the embeddings are fine-tuned for political texts, especially parliamentary bills. This would more accurately capture the content meaning of the bills, allowing for a more accurate measure of content similarity.

This paper takes a simple approach to categorising environmental bills, which can be extended in further studies by using more advanced natural language processing techniques that detect environmental issues within the content of bills. In addition, future studies could look beyond parliamentary bills by considering party manifestos or parliamentary speeches when examining how agendas are set. 

In addition, future research should apply more refined methods for measuring the public salience of environmental issues. One possible direction could be to analyse news and media outlets, which would also allow differentiation between social groups, as public opinion may vary between different demographic groups. Finally, it makes sense to extend this research beyond Swiss parties, as the growing salience of environmental issues is a global phenomenon that will influence public opinion and policy well into the future.
