---
title: "[Master Seminar Paper Title]"
output: 
  bookdown::pdf_document2:
    latex_engine: xelatex
    extra_dependencies:
      - microtype
      - float
    toc: false
    toc_depth: 4
    number_sections: false
mainfont: Times New Roman
fontsize: 12pt
bibliography: references.bib
csl: american-journal-of-political-science.csl
classoption: a4paper
lang: en-UK
header-includes:
   - \usepackage{float}
   - \floatstyle{plaintop}
   - \restylefloat{figure}
   - \usepackage{hyperref}
   - \usepackage{setspace}
   - \onehalfspacing
   - \usepackage{placeins}
   - \usepackage{booktabs}
   - \usepackage{geometry}
   - \usepackage{caption}
   - \pagenumbering{gobble} # Suppress page numbers
   - \usepackage{times}
   - \usepackage{pdflscape}
   - \usepackage[utf8]{inputenc}
   - \usepackage[hang,flushmargin]{footmisc}
   # Prevent orphans and widows
   - \widowpenalty10000
   - \clubpenalty10000
---

\onehalfspacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = normalizePath(dirname(rstudioapi::getActiveDocumentContext()$path)))
# knitr::opts_chunk$set(fig.pos = 'H', out.extra = '')
# knitr::opts_chunk$set(fig.pos = 'H')


## Setup
library(tidyverse)
library(here)
library(sf)
library(shiny)
library(lubridate)
library(haven)
library(here)
# library(strucchange) # Chow test in MA_Thesis/scripts/preliminary_exploration/02_fom_emigration/04_models.R
# library(readxl) # Read in .xls files
library(scales) # This will ensure that numbers on the y-axis are formatted with commas and without scientific notation.
# library(plm) # Panel data analysis
library(stargazer) # Exporting nice tables
# library(eurostat) # NUTS3 names
# library(slider) # Rolling averages

library(knitr)
library(kableExtra)
library(memisc)
library(pandoc)
library(pander)
library(scales)
library(fixest)
library(modelsummary)
library(bookdown)
library(gridExtra)
library(politicsR)
library(scales)

options(scipen = 0) # Enable scientific notation

# Plot Setup
gps_green <- "#84b514"
sp_red <- "#e5002b"
  
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# Load objects

# Party Strength 
# https://www.bfs.admin.ch/asset/de/27145667
ch_parties <- read_csv(here("data", "ch_parties.csv"))

# CHES
# 2019 Chapel Hill expert survey
# https://www.chesdata.eu/s/CHES2019V3.dta
ches_2019 <- haven::read_dta(here("data", "CHES2019V3.dta"))

# 2014 Chapel Hill expert survey
# https://www.chesdata.eu/s/2014_CHES_dataset_means-2.dta
ches_2014 <- haven::read_dta(here("data", "2014_CHES_dataset_means-2.dta"))

load(file = here("data", "eda.Rda"))
load(file = here("data", "all_businesses_eda.Rda"))
load(file = here("data", "all_businesses_party.Rda"))
load(file = here("data", "all_businesses_wc.Rda"))
load(file = here("data", "all_sessions.Rda"))
load(file = here("data", "google_trends", "search_term", "gt_climate_change_2004_2024.Rda"))
gt_climate_change_2004_2024_cor_plot <- gt_climate_change_2004_2024

# Selects 
# https://www.swissubase.ch/en/researcher/my-downloads/107981/19952/download-details
selects <- haven::read_dta(here("data", "swissubase_495_6_0", "495_Selects_CumulativeFile_Data_1971-2019_v2.3.0.dta"))

# 495_Selects_CumulativeFile_Doc_1971-2019_EN.html#file_backg3_mip1
mip_labels <- read_csv(here("data", "swissubase_495_6_0", "mip_labels.csv"))

# Google Trends
# Climate Change (search term)
gt_climate_change_2004_2022 <- read_csv(here("data", "google_trends", "search_term", "climate_change_2004_2022.csv"), skip = 1)
gt_climate_change_2004_2022$Month <- as.Date(paste0(gt_climate_change_2004_2022$Month, "-01"), format = "%Y-%m-%d")
gt_climate_change_2004_2022 <- gt_climate_change_2004_2022 %>% dplyr::rename(climate_change = `Climate change: (Switzerland)`)

gt_climate_change_2004_2024 <- read_csv(here("data", "google_trends", "search_term", "climate_change_2004_2024.csv"), skip = 1)
gt_climate_change_2004_2024$Month <- as.Date(paste0(gt_climate_change_2004_2024$Month, "-01"), format = "%Y-%m-%d")
gt_climate_change_2004_2024 <- gt_climate_change_2004_2024 %>% dplyr::rename(climate_change = `Climate Change: (Switzerland)`)

# Embeddings
sp_greens_all_bills_distance_ft_embeddings <- readRDS(file = here("data", "sp_greens_all_bills_distance_ft_embeddings.Rda"))
sp_greens_environmental_bills_distance_ft_embeddings <- readRDS(file = here("data", "sp_greens_environmental_bills_distance_ft_embeddings.Rda"))
```

```{r, child = '00_title.Rmd'}
```

<!-- Add this line to generate the title -->
\maketitle

<!-- Start new page after title -->
\newpage

<!-- Restart page numbering in Arabic numerals -->
\pagenumbering{arabic} 

```{r, child = '01_abstract.Rmd'}
```

\newpage

```{r, child = '02_introduction.Rmd'}
```

```{r, child = '03_lit_review.Rmd'}
```

```{r, child = '04_theory.Rmd'}
```

```{r, child = '05_case_selection.Rmd'}
```

```{r, child = '06_data_methods.Rmd'}
```

```{r, child = '07_results.Rmd'}
```

```{r, child = '08_conclusion.Rmd'}
```

\newpage

## References

<div id="refs"></div>

\newpage

```{r, child = '09_appendix.Rmd'}
```

\newpage

```{r, child = '10_authorship.Rmd'}
```

\newpage

```{r, child = '11_ai.Rmd'}
```
