# Paper

## Abstract

## Introduction

## Literature Review & Theory

### causal chain issue competition
- what makes parties put forward certain topics?
- issue competition: which topics are placed on the agenda and how do parties react to this?

- agendas are considered to be a hierarchy of issues (2010 green pedersen p. 260), that relevant actors have to pay attention to and can also influence
- 2006 sides p. 407: candidates place salient topics on their agenda (that are salient amgonst the public?) because setting a (policy) agenda and thus determining what politics is about is a form of wielding political power (1960 Schattschneider, p. 68; 1999 edwards, p. 327.)

- one way of placing topics on the agenda is to introduce them as parliamentary bills. (2010 green pedersen) describe how the “party system agenda emerges from the continuous political debate among political parties” (p. 260) which is “institutionalised in various […] ways” (p. 261), one of which is the proposal of new bills (p. 266).

- once the topics are on the agenda, parties (=candidates) react to each other’s agendas in the context of the “party system agenda” (2014 spoon p. 374). this is an “agenda-setting model of issue competition among political parties” (2010 green pedersen, p. 257).
- parties try to “emphasis advantageous issues in order to influence the party-system agenda” but “parties must also respond to whatever issues are salient at any given time” (2010 green pedersen p. 261).

- parties who are in the same bloc tend to react more responsively to each other than parties in different blocs. this is called the “party bloc effect” (2014 green p. 760; 2009 adams p. 842). this is due to ideological closeness between parties that are within the same bloc.

- this closeness allows for parties to poach voters from another ideologically close party.
- an example of this poaching is provided by (2014 spoon p. 375), who shows that if left-wing parties highlight green issues, they can reap potential electoral benefits.

- in the specific context of swiss politics, there are two further reasons why left-wing parties would want to highlight green issues

1. environmental issues have become more salient in ch in the past 20 years
- 2022 lüth, p. 171: between 2002 and 2022, the electoral importance of energy and environmental issues increases amongst voters in CH; p. 184: the salience of environmental topics is driven by voters.
- thus by highlighting salient issues, left-wing parties can set the agenda and determine what politics is about

2. sp can consider greens to be a threat
- (2014 spoon p. 366, via meguid) “mainstream parties are more likely to respond to issue when niche parties are perceived to be an electoral threat”. as the swiss greens are in the same party bloc as / ideologically close to the social demoracts and have increased their vote share in the swiss national parliament from x% to y% from 2004 to 2019, they can be perceived to be an electoral threat to the sp. thus we can expect the sp to counter this threat by poaching (back) their voters by addressing green issues.

### embeddings
`embeddings: how they show the similarity between texts; how they can encompass/convey the meaning of a text as a numerical value `

- there are different ways of measuring different party’s policy positions.
	- one way is to use party manifestos (2014 Green (see p. 752 for description of manual approach);2022 Lüth p. 177), e.g. using the Comparative Manifesto Project (CMP) (2009 adams p. 829). however, this approach relies on manual labour to 




### Hypotheses
- an increase in the salience in public opinion amongst left of centre voters of green topics leads to an increase in the similarity of parliamentary bills on green topics put forward by the greens and the social democrats
- … leads to sp putting forward parliamentary bills that are content-wise closer to green bills


## Data & Methods
- back up statement that embeddings can be used to measure distance between texts and that using this method is legit in the context of comparing parliamentary bills

- exploratory data analysis
	- current analysis (number of bills over time etc)
	- show number of bills by party strength; divide number of bills from a party by seats in parliament
- using embeddings, measure difference between texts
	- euclidean distance
	- cosine similarity
	- show difference between grouped by session and grouped by year, as there are outlier session where only few bills are introduced; maybe also filter out “Sondersessionen”, as these are very short and sometimes only cover a certain topic
- measuring distance between SP and greens over time 
	- on all topics: distance is constant
	- on environmental topics: distance decreases
	- differentiate between bills that only have the tag “environment” and bills with the most common co-tag, e.g. “environment” and “finance” 
- does one party move closer to the other party or do both parties move?

### Operationalisation
- Environmental Topic saliency
	- Google Trends?
	- Worry Barometer?
	- selects survey, as done by 2022 Lütch p. 171

### Model
y = distance between sp and greens
x = (lagged?) topic salience

## Conclusion
- Future research:
	- Use fine tuned embeddings
	- look at topic saliency more specifically amongst left-wing and green voters